// Example graphs for /playground. The .gfa files are also what
// crates/reduce/src/tests.rs asserts on, so the page and the tests read the same
// bytes and can't drift apart.
//
// Synthetic fixtures are small but realistic: a reference backbone with flanks, a
// single variant site in the middle, and several haplotypes (so nodes carry real
// coverage and branch like a real subgraph). Each carries an `expect` block
// describing what the pop pass should do, which the page checks live.
//
// Real fixtures are unsimplified `query --raw` output for loci the app itself
// offers as examples, generated by scripts/fetch-fixture.mjs.
import snpGfa from './fixtures/snp.gfa?raw';
import smallInsGfa from './fixtures/small_ins.gfa?raw';
import largeInsGfa from './fixtures/large_ins.gfa?raw';
import largeDelGfa from './fixtures/large_del.gfa?raw';
import smallDelGfa from './fixtures/small_del.gfa?raw';
import multiallelicGfa from './fixtures/multiallelic.gfa?raw';
import mixedGfa from './fixtures/mixed.gfa?raw';
import mnpGfa from './fixtures/mnp.gfa?raw';
import nestedGfa from './fixtures/nested.gfa?raw';
import cyclicGfa from './fixtures/cyclic.gfa?raw';
import longRunGfa from './fixtures/long_run.gfa?raw';
import c4a from './fixtures/c4a.gfa?raw';
import smn1 from './fixtures/smn1.gfa?raw';
import chr20_200kb from './fixtures/chr20_200kb.gfa?raw';

export interface FixtureExpect {
	/** Collapsed sites the pop pass should produce. */
	sites: number;
	/** Total non-reference interior nodes removed across all sites. */
	nodesRemoved: number;
	/** Removed interior nodes that were single-base (SNPs). */
	snpCount: number;
	/** Total non-reference interior bases condensed. */
	basesRemoved: number;
	/** Segment ids that must be gone after the pop pass. */
	removedNodes?: string[];
	/** Segment ids that must survive the pop pass. */
	keptNodes?: string[];
	/** Segment count after the full simplify (pop + unchop), if pinned. */
	segmentsAfterSimplify?: number;
}

export interface Fixture {
	id: string;
	label: string;
	description: string;
	kind: 'synthetic' | 'real';
	referenceSample: string;
	gfaText: string;
	expect?: FixtureExpect;
}

const REF = 'ref';

// --- synthetic fixtures -------------------------------------------------------
// Skeleton: reference nodes 1..5 form the backbone (with 50 bp flanks 1 and 5,
// 20 bp anchors 2 and 4, and the variable middle 3); alt alleles use ids 20+.

const snp: Fixture = {
	id: 'snp',
	label: 'Single SNP',
	description: 'One 1 bp substitution carried by 3 of 5 haplotypes — collapses to reference.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: snpGfa,
	expect: {
		sites: 1,
		nodesRemoved: 1,
		snpCount: 1,
		basesRemoved: 1,
		removedNodes: ['20'],
		keptNodes: ['1', '2', '3', '4', '5'],
		segmentsAfterSimplify: 1
	}
};

const smallIns: Fixture = {
	id: 'small_ins',
	label: 'Small insertion',
	description: '4 bp insertion (no reference skipped) carried by 2 of 4 haplotypes — collapses.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: smallInsGfa,
	expect: {
		sites: 1,
		nodesRemoved: 1,
		snpCount: 0,
		basesRemoved: 4,
		removedNodes: ['20'],
		keptNodes: ['1', '2', '3', '4'],
		segmentsAfterSimplify: 1
	}
};

const largeIns: Fixture = {
	id: 'large_ins',
	label: 'Large insertion (kept)',
	description: '60 bp insertion — exceeds threshold, preserved as a visible alt allele.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: largeInsGfa,
	expect: {
		sites: 0,
		nodesRemoved: 0,
		snpCount: 0,
		basesRemoved: 0,
		keptNodes: ['1', '2', '3', '4', '30']
	}
};

const largeDel: Fixture = {
	id: 'large_del',
	label: 'Large deletion (kept)',
	description:
		'Edge skipping a 60 bp reference node — the flagged case: tiny alt allele, big event, must be preserved.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: largeDelGfa,
	expect: {
		sites: 0,
		nodesRemoved: 0,
		snpCount: 0,
		basesRemoved: 0,
		keptNodes: ['1', '2', '3', '4', '5']
	}
};

const smallDel: Fixture = {
	id: 'small_del',
	label: 'Small deletion',
	description: 'Edge skipping a 3 bp reference node — collapses (haplotypes rerouted onto reference).',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: smallDelGfa,
	expect: {
		sites: 1,
		nodesRemoved: 0,
		snpCount: 0,
		basesRemoved: 0,
		keptNodes: ['1', '2', '3', '4', '5'],
		segmentsAfterSimplify: 1
	}
};

const multiallelic: Fixture = {
	id: 'multiallelic',
	label: 'Multiallelic SNPs',
	description: 'Two parallel 1 bp alt alleles at one site — both collapse.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: multiallelicGfa,
	expect: {
		sites: 1,
		nodesRemoved: 2,
		snpCount: 2,
		basesRemoved: 2,
		removedNodes: ['20', '21'],
		keptNodes: ['1', '2', '3', '4', '5'],
		segmentsAfterSimplify: 1
	}
};

const mixed: Fixture = {
	id: 'mixed',
	label: 'SNP + nearby SV',
	description:
		'A 1 bp SNP at one site and a 60 bp insertion at the next — the SNP collapses, the SV is preserved.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: mixedGfa,
	expect: {
		sites: 1,
		nodesRemoved: 1,
		snpCount: 1,
		basesRemoved: 1,
		removedNodes: ['20'],
		keptNodes: ['1', '2', '3', '4', '5', '30']
	}
};

const mnp: Fixture = {
	id: 'mnp',
	label: 'MNP / overlapping small variants',
	description:
		'Two adjacent 1 bp sites tangled by haplotypes carrying both — a complex site whose longest path is still < N, so it collapses to reference.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: mnpGfa,
	expect: {
		sites: 1,
		nodesRemoved: 2,
		snpCount: 2,
		basesRemoved: 2,
		removedNodes: ['20', '21'],
		keptNodes: ['1', '2', '3', '4', '5'],
		segmentsAfterSimplify: 1
	}
};

const nested: Fixture = {
	id: 'nested',
	label: 'Large complex bubble (kept)',
	description:
		'A branching alt region (a bubble within the bubble) whose paths exceed N bases — the whole complex site is left intact.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: nestedGfa,
	expect: {
		sites: 0,
		nodesRemoved: 0,
		snpCount: 0,
		basesRemoved: 0,
		keptNodes: ['1', '2', '3', '4', '20', '21', '22']
	}
};

const cyclic: Fixture = {
	id: 'cyclic',
	label: 'Cyclic alt (kept)',
	description: 'An alt node with a self-loop (a tandem-repeat-like cycle) — never collapsed.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: cyclicGfa,
	expect: {
		sites: 0,
		nodesRemoved: 0,
		snpCount: 0,
		basesRemoved: 0,
		keptNodes: ['1', '2', '3', '4', '20']
	}
};

const longRun: Fixture = {
	id: 'long_run',
	label: 'Long linear run (unchop)',
	description: 'Six reference nodes in a row with no variation — unchop merges them into one.',
	kind: 'synthetic',
	referenceSample: REF,
	gfaText: longRunGfa,
	expect: {
		sites: 0,
		nodesRemoved: 0,
		snpCount: 0,
		basesRemoved: 0,
		segmentsAfterSimplify: 1
	}
};

export const SYNTHETIC_FIXTURES: Fixture[] = [
	snp,
	smallIns,
	largeIns,
	largeDel,
	smallDel,
	multiallelic,
	mixed,
	mnp,
	nested,
	cyclic,
	longRun
];

// --- real fixtures ------------------------------------------------------------

export const REAL_FIXTURES: Fixture[] = [
	{
		id: 'c4a',
		label: 'C4A (real, MHC class III)',
		description:
			"Complement C4A on GRCh38, one of the app's example loci. A real MHC gene rather than an " +
			'arbitrary slice of the region: C4 is copy-number variable and carries the C4A/C4B paralogy, ' +
			'so the graph has genuine structural variation to leave alone alongside the SNPs it collapses.',
		kind: 'real',
		referenceSample: 'GRCh38',
		gfaText: c4a
	},
	{
		id: 'smn1',
		label: 'SMN1 (real, segmental duplication)',
		description:
			"The app's default locus. SMN1/SMN2 are near-identical paralogs, so a lot of the graph is " +
			'repetitive — a good test that unchop collapses long runs without the pop pass touching the ' +
			'duplication structure itself.',
		kind: 'real',
		referenceSample: 'GRCh38',
		gfaText: smn1
	},
	{
		id: 'chr20_200kb',
		label: 'chr20 ~200 kb (real, complex)',
		description:
			'chr20:30,000,000–30,200,000 from HPRC GRCh38 — 9,892 nodes, 422 haplotype walks (vs ~90-100 typical; ' +
			'likely a segmental duplication). Simplifies far less (only ~5.7×, to ~1,750 nodes) than the MHC ' +
			'examples (~50×) because most of its sites are large/nested and correctly left untouched — this is ' +
			'the practical scaling ceiling for the current single-pass algorithm: layout alone takes ~15-20s in ' +
			'the browser (vs ~0.5s for MHC). Bigger chr20 windows we benchmarked (500kb/1Mb) pushed layout past ' +
			'20-45s+, well beyond what feels reasonable to wait for interactively.',
		kind: 'real',
		referenceSample: 'GRCh38',
		gfaText: chr20_200kb
	}
];

export const ALL_FIXTURES: Fixture[] = [...SYNTHETIC_FIXTURES, ...REAL_FIXTURES];
